/**
 * Job Notification Tracker — 60 realistic Indian tech jobs
 */

var JOBS = [
  {
    id: 'j1',
    title: 'SDE Intern',
    company: 'Amazon',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Python', 'Data Structures', 'Algorithms'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.amazon.jobs/en/jobs/example-1',
    description: 'Join Amazon\'s SDE internship program. Work on real projects alongside experienced engineers. Learn best practices in software development and gain exposure to large-scale systems.'
  },
  {
    id: 'j2',
    title: 'Graduate Engineer Trainee',
    company: 'TCS',
    location: 'Chennai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'SQL', 'HTML', 'CSS', 'JavaScript'],
    source: 'Naukri',
    postedDaysAgo: 3,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.tcs.com/careers/example',
    description: 'Tata Consultancy Services is hiring fresh graduates for its GET program. Comprehensive training in software development and delivery. Rotational assignments across projects.'
  },
  {
    id: 'j3',
    title: 'Junior Backend Developer',
    company: 'Razorpay',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Node.js', 'PostgreSQL', 'Redis', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://razorpay.com/jobs/example',
    description: 'Build scalable payment infrastructure at Razorpay. Work with microservices, handle high-volume transactions, and contribute to India\'s leading payment gateway.'
  },
  {
    id: 'j4',
    title: 'Frontend Intern',
    company: 'Flipkart',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'CSS', 'HTML'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.flipkartcareers.com/example',
    description: 'Work on Flipkart\'s consumer-facing web applications. Build responsive, performant interfaces used by millions of customers. Mentorship from senior frontend engineers.'
  },
  {
    id: 'j5',
    title: 'QA Intern',
    company: 'Infosys',
    location: 'Pune',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Manual Testing', 'Selenium', 'SQL', 'JIRA'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.infosys.com/careers/example',
    description: 'Join Infosys\' quality assurance team. Learn test automation, understand SDLC, and ensure delivery of high-quality software. Structured internship with clear learning outcomes.'
  },
  {
    id: 'j6',
    title: 'Data Analyst Intern',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Excel', 'Tableau'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://careers.swiggy.com/example',
    description: 'Analyze Swiggy\'s operational and user data. Build dashboards, derive insights for business decisions. Work with large datasets in a fast-paced food delivery environment.'
  },
  {
    id: 'j7',
    title: 'Java Developer (0-1)',
    company: 'Wipro',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Spring Boot', 'Hibernate', 'MySQL'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://careers.wipro.com/example',
    description: 'Develop enterprise applications using Java and Spring. Work on client projects across domains. Structured onboarding and technical mentorship provided.'
  },
  {
    id: 'j8',
    title: 'Python Developer (Fresher)',
    company: 'Zoho',
    location: 'Chennai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'PostgreSQL', 'REST APIs'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.zoho.com/careers/example',
    description: 'Build products at Zoho, one of India\'s largest product companies. Work on cloud software used globally. Bootcamp-style training for freshers.'
  },
  {
    id: 'j9',
    title: 'React Developer (1-3)',
    company: 'PhonePe',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Redux', 'Jest'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.phonepe.com/careers/example',
    description: 'Build the frontend of India\'s largest UPI app. Work on performance, accessibility, and scale. Millions of users rely on the interfaces you will build.'
  },
  {
    id: 'j10',
    title: 'SDE Intern',
    company: 'Microsoft',
    location: 'Hyderabad',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C++', 'Algorithms', 'Problem Solving'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://careers.microsoft.com/example',
    description: 'Microsoft IDC Hyderabad offers internships across Azure, Office, and Windows. Work on projects that impact billions of users worldwide.'
  },
  {
    id: 'j11',
    title: 'Graduate Engineer Trainee',
    company: 'Accenture',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Python', 'Cloud', 'Agile'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.accenture.com/in-en/careers/example',
    description: 'Accenture\'s GET program trains fresh graduates in cutting-edge technologies. Work on digital transformation projects for global clients.'
  },
  {
    id: 'j12',
    title: 'Junior Backend Developer',
    company: 'CRED',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Go', 'PostgreSQL', 'Kafka', 'Redis'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://cred.club/careers/example',
    description: 'Build backend systems for CRED\'s fintech products. Work on high-throughput, low-latency systems. Strong engineering culture.'
  },
  {
    id: 'j13',
    title: 'Frontend Intern',
    company: 'Freshworks',
    location: 'Chennai',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.freshworks.com/company/careers/example',
    description: 'Build UI for Freshworks\' SaaS products. Work on customer-facing features. Mentorship from experienced frontend engineers.'
  },
  {
    id: 'j14',
    title: 'Data Analyst Intern',
    company: 'Paytm',
    location: 'Noida',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Excel', 'Power BI'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://paytm.com/careers/example',
    description: 'Analyze payment and user data at Paytm. Support business teams with insights. Learn data engineering and analytics in fintech.'
  },
  {
    id: 'j15',
    title: 'Java Developer (0-1)',
    company: 'Cognizant',
    location: 'Chennai',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Java', 'Spring', 'SQL', 'Git'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://careers.cognizant.com/example',
    description: 'Develop enterprise applications for Cognizant clients. Work on banking, healthcare, or retail projects. Structured career path.'
  },
  {
    id: 'j16',
    title: 'Python Developer (Fresher)',
    company: 'Dell',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Python', 'Linux', 'Scripting', 'Automation'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://jobs.dell.com/example',
    description: 'Join Dell\'s infrastructure software team. Build automation tools and scripts. Work on products used by enterprises worldwide.'
  },
  {
    id: 'j17',
    title: 'React Developer (1-3)',
    company: 'Juspay',
    location: 'Bangalore',
    mode: 'Remote',
    experience: '1-3',
    skills: ['React', 'JavaScript', 'Payment Gateways'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://juspay.io/careers/example',
    description: 'Build payment SDKs and UIs at Juspay. Work on checkout experiences for top apps. Strong focus on performance and reliability.'
  },
  {
    id: 'j18',
    title: 'SDE Intern',
    company: 'Google',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Algorithms', 'Data Structures', 'C++', 'Python'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://careers.google.com/example',
    description: 'Google Bangalore offers internships across Search, Ads, and Cloud. Work on problems at internet scale. Highly competitive program.'
  },
  {
    id: 'j19',
    title: 'Graduate Engineer Trainee',
    company: 'Capgemini',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'SQL', 'Web Technologies'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.capgemini.com/in-en/careers/example',
    description: 'Capgemini\'s GET program offers training in digital technologies. Work on projects for global clients. Clear progression path.'
  },
  {
    id: 'j20',
    title: 'Junior Backend Developer',
    company: 'Postman',
    location: 'Bangalore',
    mode: 'Remote',
    experience: '0-1',
    skills: ['Node.js', 'MongoDB', 'API Development'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.postman.com/company/careers/example',
    description: 'Build APIs and backend services for Postman. Work on the product used by millions of developers. Remote-first culture.'
  },
  {
    id: 'j21',
    title: 'Frontend Intern',
    company: 'BrowserStack',
    location: 'Mumbai',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'Testing'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.browserstack.com/careers/example',
    description: 'Work on BrowserStack\'s web dashboard. Build tools for developers testing across devices. Collaborative, product-focused team.'
  },
  {
    id: 'j22',
    title: 'QA Intern',
    company: 'Thoughtworks',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Testing', 'Automation', 'Agile'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.thoughtworks.com/careers/example',
    description: 'Learn test-driven development at Thoughtworks. Work on quality practices. Exposure to diverse tech stacks and client projects.'
  },
  {
    id: 'j23',
    title: 'Data Analyst Intern',
    company: 'ShareChat',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Data Visualization'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://sharechat.com/careers/example',
    description: 'Analyze user behavior and content metrics at ShareChat. Support product and growth teams. Work with large-scale data.'
  },
  {
    id: 'j24',
    title: 'Java Developer (0-1)',
    company: 'IBM',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Cloud', 'Microservices'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.ibm.com/in-en/employment/example',
    description: 'Develop cloud-native applications at IBM. Work on Watson, Cloud Pak, or hybrid cloud solutions. Strong learning environment.'
  },
  {
    id: 'j25',
    title: 'Python Developer (Fresher)',
    company: 'Oracle',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'SQL', 'Linux'],
    source: 'LinkedIn',
    postedDaysAgo: 7,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.oracle.com/in/corporate/careers/example',
    description: 'Join Oracle\'s development teams. Work on database, cloud, or applications. Comprehensive training for freshers.'
  },
  {
    id: 'j26',
    title: 'React Developer (1-3)',
    company: 'CleverTap',
    location: 'Mumbai',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Redux'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://clevertap.com/careers/example',
    description: 'Build CleverTap\'s marketing analytics dashboard. Work on real-time visualizations. Product-led growth company.'
  },
  {
    id: 'j27',
    title: 'SDE Intern',
    company: 'Adobe',
    location: 'Noida',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C++', 'Algorithms', 'Creative Tools'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://careers.adobe.com/example',
    description: 'Adobe India offers internships in creative cloud, document cloud, and experience cloud. Work on products used by millions.'
  },
  {
    id: 'j28',
    title: 'Graduate Engineer Trainee',
    company: 'L&T Infotech',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Dot Net', 'Database'],
    source: 'Naukri',
    postedDaysAgo: 9,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.lntinfotech.com/careers/example',
    description: 'LTI\'s GET program trains engineers for digital transformation. Work on enterprise projects. Strong brand and stability.'
  },
  {
    id: 'j29',
    title: 'Junior Backend Developer',
    company: 'Unacademy',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Python', 'Django', 'PostgreSQL'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://unacademy.com/careers/example',
    description: 'Build backend for India\'s largest learning platform. Work on content delivery, payments, and user engagement. High-growth startup.'
  },
  {
    id: 'j30',
    title: 'Frontend Intern',
    company: 'Dunzo',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'Mobile Web'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.dunzo.com/careers/example',
    description: 'Build user-facing features for Dunzo\'s hyperlocal delivery app. Work on responsive, fast-loading interfaces. Impact millions of users.'
  },
  {
    id: 'j31',
    title: 'Data Analyst Intern',
    company: 'Ola',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Analytics'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.olacabs.com/careers/example',
    description: 'Analyze ride and user data at Ola. Support operations and product teams. Work with large-scale mobility data.'
  },
  {
    id: 'j32',
    title: 'Java Developer (0-1)',
    company: 'SAP',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'SAP Technologies', 'SQL'],
    source: 'LinkedIn',
    postedDaysAgo: 5,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://jobs.sap.com/example',
    description: 'Develop SAP solutions and extensions. Work on enterprise software used globally. Strong training and certification support.'
  },
  {
    id: 'j33',
    title: 'Python Developer (Fresher)',
    company: 'HackerRank',
    location: 'Bangalore',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'React'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.hackerrank.com/careers/example',
    description: 'Build HackerRank\'s assessment platform. Work on coding challenges and interview tools. Remote-first, developer-focused.'
  },
  {
    id: 'j34',
    title: 'React Developer (1-3)',
    company: 'MakeMyTrip',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'JavaScript', 'Travel Tech'],
    source: 'Indeed',
    postedDaysAgo: 6,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://careers.makemytrip.com/example',
    description: 'Build MakeMyTrip\'s web experience. Work on booking flows, search, and personalization. India\'s leading travel platform.'
  },
  {
    id: 'j35',
    title: 'SDE Intern',
    company: 'VMware',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C', 'C++', 'Networking'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://careers.vmware.com/example',
    description: 'VMware Bangalore offers internships in cloud, networking, and security. Work on infrastructure software. Strong engineering culture.'
  },
  {
    id: 'j36',
    title: 'Graduate Engineer Trainee',
    company: 'Tech Mahindra',
    location: 'Pune',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Cloud', 'Digital'],
    source: 'Naukri',
    postedDaysAgo: 10,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.techmahindra.com/careers/example',
    description: 'Tech Mahindra\'s GET program focuses on digital transformation. Work on 5G, cloud, and automation. Diverse project opportunities.'
  },
  {
    id: 'j37',
    title: 'Junior Backend Developer',
    company: 'Rivigo',
    location: 'Gurgaon',
    mode: 'Onsite',
    experience: '0-1',
    skills: ['Python', 'Node.js', 'MongoDB'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://rivigo.com/careers/example',
    description: 'Build logistics technology at Rivigo. Work on fleet management and optimization. Tech-first approach to trucking.'
  },
  {
    id: 'j38',
    title: 'Frontend Intern',
    company: 'PolicyBazaar',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'HTML', 'CSS'],
    source: 'Indeed',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.policybazaar.com/careers/example',
    description: 'Build PolicyBazaar\'s insurance comparison UI. Work on conversion-optimized interfaces. India\'s largest insurtech.'
  },
  {
    id: 'j39',
    title: 'QA Intern',
    company: 'Licious',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Manual Testing', 'API Testing', 'Selenium'],
    source: 'Naukri',
    postedDaysAgo: 5,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.licious.in/careers/example',
    description: 'Ensure quality of Licious\' e-commerce platform. Learn test automation. Fast-growing D2C brand.'
  },
  {
    id: 'j40',
    title: 'Data Analyst Intern',
    company: 'Groww',
    location: 'Bangalore',
    mode: 'Remote',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Finance Analytics'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://groww.in/careers/example',
    description: 'Analyze investment and user data at Groww. Support product and growth. India\'s leading investment platform.'
  },
  {
    id: 'j41',
    title: 'Java Developer (0-1)',
    company: 'Myntra',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Spring', 'Kafka'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://www.myntra.com/careers/example',
    description: 'Build Myntra\'s e-commerce backend. Work on catalog, search, and order systems. Fashion tech at scale.'
  },
  {
    id: 'j42',
    title: 'Python Developer (Fresher)',
    company: 'Deutsche Bank',
    location: 'Pune',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'SQL', 'Finance'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://careers.db.com/example',
    description: 'Join Deutsche Bank\'s technology team. Work on financial systems. Strong training and global exposure.'
  },
  {
    id: 'j43',
    title: 'React Developer (1-3)',
    company: 'Nykaa',
    location: 'Mumbai',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'JavaScript', 'E-commerce'],
    source: 'Indeed',
    postedDaysAgo: 1,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.nykaa.com/careers/example',
    description: 'Build Nykaa\'s beauty e-commerce experience. Work on discovery, personalization, and conversion. Leading beauty platform.'
  },
  {
    id: 'j44',
    title: 'SDE Intern',
    company: 'Intuit',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Python', 'Cloud'],
    source: 'LinkedIn',
    postedDaysAgo: 2,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.intuit.com/careers/example',
    description: 'Intuit India offers internships in TurboTax, QuickBooks, and Mailchimp. Work on products used by small businesses globally.'
  },
  {
    id: 'j45',
    title: 'Graduate Engineer Trainee',
    company: 'HCL Technologies',
    location: 'Noida',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Dot Net', 'Testing'],
    source: 'Naukri',
    postedDaysAgo: 8,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.hcltech.com/careers/example',
    description: 'HCL\'s GET program trains engineers for IT services. Work on diverse client projects. Large organization with many opportunities.'
  },
  {
    id: 'j46',
    title: 'Junior Backend Developer',
    company: 'Meesho',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Python', 'Django', 'PostgreSQL'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://careers.meesho.com/example',
    description: 'Build Meesho\'s reseller platform backend. Work on orders, catalog, and payments. India\'s leading social commerce.'
  },
  {
    id: 'j47',
    title: 'Frontend Intern',
    company: 'Lenskart',
    location: 'Faridabad',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'E-commerce'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.lenskart.com/careers/example',
    description: 'Build Lenskart\'s online eyewear experience. Work on virtual try-on and shopping flows. Omnichannel retail tech.'
  },
  {
    id: 'j48',
    title: 'Data Analyst Intern',
    company: 'Cult.fit',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'User Analytics'],
    source: 'Naukri',
    postedDaysAgo: 4,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.cult.fit/careers/example',
    description: 'Analyze fitness and wellness data at Cult.fit. Support growth and product. India\'s leading fitness brand.'
  },
  {
    id: 'j49',
    title: 'Java Developer (0-1)',
    company: 'Swiggy',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Kafka', 'Microservices'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://careers.swiggy.com/example',
    description: 'Build Swiggy\'s food delivery platform. Work on orders, logistics, and scale. India\'s leading food tech.'
  },
  {
    id: 'j50',
    title: 'Python Developer (Fresher)',
    company: 'InMobi',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'Data Processing', 'Ad Tech'],
    source: 'LinkedIn',
    postedDaysAgo: 6,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.inmobi.com/company/careers/example',
    description: 'Join InMobi\'s ad tech team. Work on data pipelines and ML systems. India\'s first unicorn.'
  },
  {
    id: 'j51',
    title: 'React Developer (1-3)',
    company: 'Urban Company',
    location: 'Gurgaon',
    mode: 'Hybrid',
    experience: '1-3',
    skills: ['React', 'TypeScript', 'Mobile Web'],
    source: 'Indeed',
    postedDaysAgo: 2,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://www.urbancompany.com/careers/example',
    description: 'Build Urban Company\'s service booking platform. Work on customer and partner apps. India\'s leading home services.'
  },
  {
    id: 'j52',
    title: 'SDE Intern',
    company: 'Cisco',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['C', 'Python', 'Networking'],
    source: 'LinkedIn',
    postedDaysAgo: 3,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://jobs.cisco.com/example',
    description: 'Cisco Bangalore offers internships in networking and collaboration. Work on products powering the internet.'
  },
  {
    id: 'j53',
    title: 'Graduate Engineer Trainee',
    company: 'Mindtree',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Java', 'Cloud', 'Digital'],
    source: 'Naukri',
    postedDaysAgo: 9,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.mindtree.com/careers/example',
    description: 'Mindtree\'s GET program focuses on digital engineering. Work on cloud, data, and IoT. Part of Larsen & Toubro.'
  },
  {
    id: 'j54',
    title: 'Junior Backend Developer',
    company: 'Slice',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Node.js', 'PostgreSQL', 'Fintech'],
    source: 'LinkedIn',
    postedDaysAgo: 0,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://slice.it/careers/example',
    description: 'Build Slice\'s credit card backend. Work on payments and user experience. Fintech for Gen Z.'
  },
  {
    id: 'j55',
    title: 'Frontend Intern',
    company: 'NoBroker',
    location: 'Bangalore',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['React', 'JavaScript', 'Real Estate'],
    source: 'Indeed',
    postedDaysAgo: 5,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.nobroker.in/careers/example',
    description: 'Build NoBroker\'s property search experience. Work on maps and listings. India\'s leading proptech.'
  },
  {
    id: 'j56',
    title: 'QA Intern',
    company: 'Practo',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: 'Fresher',
    skills: ['Testing', 'Mobile', 'Healthcare'],
    source: 'Naukri',
    postedDaysAgo: 6,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.practo.com/careers/example',
    description: 'Ensure quality of Practo\'s healthcare platform. Work on doctor discovery and appointments. Leading healthtech.'
  },
  {
    id: 'j57',
    title: 'Data Analyst Intern',
    company: 'Zepto',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['SQL', 'Python', 'Supply Chain'],
    source: 'LinkedIn',
    postedDaysAgo: 1,
    salaryRange: '₹15k–₹40k/month Internship',
    applyUrl: 'https://www.zeptonow.com/careers/example',
    description: 'Analyze Zepto\'s quick commerce data. Support operations and growth. 10-minute delivery at scale.'
  },
  {
    id: 'j58',
    title: 'Java Developer (0-1)',
    company: 'BYJU\'S',
    location: 'Bangalore',
    mode: 'Hybrid',
    experience: '0-1',
    skills: ['Java', 'Spring', 'EdTech'],
    source: 'Naukri',
    postedDaysAgo: 7,
    salaryRange: '6–10 LPA',
    applyUrl: 'https://byjus.com/careers/example',
    description: 'Build BYJU\'S learning platform. Work on content delivery and assessments. India\'s largest edtech.'
  },
  {
    id: 'j59',
    title: 'Python Developer (Fresher)',
    company: 'Rebel Foods',
    location: 'Mumbai',
    mode: 'Onsite',
    experience: 'Fresher',
    skills: ['Python', 'Django', 'Cloud Kitchens'],
    source: 'LinkedIn',
    postedDaysAgo: 4,
    salaryRange: '3–5 LPA',
    applyUrl: 'https://www.rebelfoods.com/careers/example',
    description: 'Build Rebel Foods\' cloud kitchen technology. Work on orders and operations. India\'s largest cloud kitchen network.'
  },
  {
    id: 'j60',
    title: 'React Developer (1-3)',
    company: 'Instamojo',
    location: 'Bangalore',
    mode: 'Remote',
    experience: '1-3',
    skills: ['React', 'JavaScript', 'Payments'],
    source: 'Indeed',
    postedDaysAgo: 3,
    salaryRange: '10–18 LPA',
    applyUrl: 'https://instamojo.com/careers/example',
    description: 'Build Instamojo\'s SMB commerce platform. Work on payments and storefronts. Enabling small businesses online.'
  }
];
